[package]
name = "MessageBoard"
version = "1.0.0"
authors = []

[addresses]
addrx = "0xbfff0d917e8eeb80a06b4631ef8f1bfc2b6008ae4863bb275bb2435799fbae2e"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }

[dev-dependencies]
